trigger:
  - main
# trigger is set to main because this pipelien shold be execute only when something is added in the main branch.

variables:
  - group: dbw-cicd-dev
  - name: vmImageName
    value: "windows-latest"
  - name: notebooksPath
    value: "notebook"
    # here notebooksPath is set to notebook becuase we will deploy only those notebooks which are present in the notebook folder.


pool:
  vmImage: $(vmImageName)

stages:
    # here we are calling templates file
  - template: templates/deploy-notebooks.yml
    # all these params gonna be passed in deploy-notebooks.yml file
    parameters:
      stageId: "Deploy_to_Dev_Environment"
      env: "dev"
      environmentName: $(dev-environment-name)
      resourceGroupName: $(dev-resource-group-name)
      serviceConnection: $(dev-service-connection-name)
      notebooksPath: $(notebooksPath)